site_name: 'Fridge Planner (Temporary Name)'
site_description: 'This project will help anybody to register what they have in their fridge, what recipes they know, and what they need to buy to manage them.'
site_author: 'Riccardo Sartori'
copyright: '2020 Riccardo Sartori'
repo_url: 'https://github.com/SartoRiccardo/fridge-app'

nav:
    - 'Project Charter': 'project_charter.md'

theme:
    name: readthedocs
